class hud_farming {
    idd = -1;
    duration = 1e+011;
    name = "hud_farming";
    onLoad = "uiNamespace setVariable ['hud_farming',_this select 0]";
    objects[] = {};

    class controls
    {
        class t1: RscStructuredText {idc = -1;};
        class t2: RscStructuredText {idc = -1;};
        class t3: RscStructuredText {idc = -1;};
        class t4: RscStructuredText {idc = -1;};
        class t5: RscStructuredText {idc = -1;};
        class t6: RscStructuredText {idc = -1;};
        class t7: RscStructuredText {idc = -1;};
        class t8: RscStructuredText {idc = -1;};
        class t9: RscStructuredText {idc = -1;};
        class t10: RscStructuredText {idc = -1;};
        class t11: RscStructuredText {idc = -1;};
        class t12: RscStructuredText {idc = -1;};
        class t13: RscStructuredText {idc = -1;};
        class t14: RscStructuredText {idc = -1;};
        class t15: RscStructuredText {idc = -1;};
        class t16: RscStructuredText {idc = -1;};
        class t17: RscStructuredText {idc = -1;};
        class t18: RscStructuredText {idc = -1;};
        class t19: RscStructuredText {idc = -1;};
        class t20: RscStructuredText {idc = -1;};
        class t21: RscStructuredText {idc = -1;};
        class t22: RscStructuredText {idc = -1;};
        class t23: RscStructuredText {idc = -1;};
        class t24: RscStructuredText {idc = -1;};
        class t25: RscStructuredText {idc = -1;};
        class t26: RscStructuredText {idc = -1;};
        class t27: RscStructuredText {idc = -1;};
        class t28: RscStructuredText {idc = -1;};
        class t29: RscStructuredText {idc = -1;};
        class t30: RscStructuredText {idc = -1;};
        class t31: RscStructuredText {idc = -1;};
        class t32: RscStructuredText {idc = -1;};
        class t33: RscStructuredText {idc = -1;};
        class t34: RscStructuredText {idc = -1;};
        class t35: RscStructuredText {idc = -1;};
        class t36: RscStructuredText {idc = -1;};
        class t37: RscStructuredText {idc = -1;};
        class t38: RscStructuredText {idc = -1;};
        class t39: RscStructuredText {idc = -1;};
        class t40: RscStructuredText {idc = -1;};
        class t41: RscStructuredText {idc = -1;};
        class t42: RscStructuredText {idc = -1;};
        class t43: RscStructuredText {idc = -1;};
        class t44: RscStructuredText {idc = -1;};
        class t45: RscStructuredText {idc = -1;};
        class t46: RscStructuredText {idc = -1;};
        class t47: RscStructuredText {idc = -1;};
        class t48: RscStructuredText {idc = -1;};
        class t49: RscStructuredText {idc = -1;};
        class t50: RscStructuredText {idc = -1;};
    };
};
